/* Autogenerated - do not fiddle */
if(typeof(Contracts) === "undefined") var Contracts={};
(function(module, Contracts) {
    var data = {
        address: "0xa134F61059b4CCcd031F2ad0C209dAf0d8d6c584",
        network: "Ropsten",
        endpoint: "",
        abi: [
            {
                "constant": false,
                "inputs": [
                    {
                        "name": "id",
                        "type": "uint256"
                    }
                ],
                "name": "cancel",
                "outputs": [],
                "payable": false,
                "stateMutability": "nonpayable",
                "type": "function"
            },
            {
                "constant": false,
                "inputs": [
                    {
                        "name": "id",
                        "type": "uint256"
                    },
                    {
                        "name": "newFee",
                        "type": "uint256"
                    }
                ],
                "name": "modifyFee",
                "outputs": [],
                "payable": false,
                "stateMutability": "nonpayable",
                "type": "function"
            },
            {
                "constant": false,
                "inputs": [
                    {
                        "name": "_licensor",
                        "type": "address"
                    },
                    {
                        "name": "_licensee",
                        "type": "address"
                    },
                    {
                        "name": "_assetId",
                        "type": "bytes32"
                    },
                    {
                        "name": "_fee",
                        "type": "uint256"
                    }
                ],
                "name": "create",
                "outputs": [],
                "payable": false,
                "stateMutability": "nonpayable",
                "type": "function"
            },
            {
                "constant": false,
                "inputs": [
                    {
                        "name": "id",
                        "type": "uint256"
                    }
                ],
                "name": "approve",
                "outputs": [],
                "payable": true,
                "stateMutability": "payable",
                "type": "function"
            },
            {
                "constant": true,
                "inputs": [
                    {
                        "name": "",
                        "type": "uint256"
                    }
                ],
                "name": "licenseContracts",
                "outputs": [
                    {
                        "name": "licensor",
                        "type": "address"
                    },
                    {
                        "name": "licensee",
                        "type": "address"
                    },
                    {
                        "name": "assetId",
                        "type": "bytes32"
                    },
                    {
                        "name": "fee",
                        "type": "uint256"
                    },
                    {
                        "name": "licensorApproved",
                        "type": "bool"
                    },
                    {
                        "name": "licenseeApproved",
                        "type": "bool"
                    },
                    {
                        "name": "executed",
                        "type": "bool"
                    },
                    {
                        "name": "canceled",
                        "type": "bool"
                    }
                ],
                "payable": false,
                "stateMutability": "view",
                "type": "function"
            },
            {
                "anonymous": false,
                "inputs": [
                    {
                        "indexed": true,
                        "name": "initiator",
                        "type": "address"
                    },
                    {
                        "indexed": false,
                        "name": "contractId",
                        "type": "uint256"
                    }
                ],
                "name": "Create",
                "type": "event"
            },
            {
                "anonymous": false,
                "inputs": [
                    {
                        "indexed": true,
                        "name": "initiator",
                        "type": "address"
                    },
                    {
                        "indexed": false,
                        "name": "contractId",
                        "type": "uint256"
                    }
                ],
                "name": "Modify",
                "type": "event"
            },
            {
                "anonymous": false,
                "inputs": [
                    {
                        "indexed": true,
                        "name": "initiator",
                        "type": "address"
                    },
                    {
                        "indexed": false,
                        "name": "contractId",
                        "type": "uint256"
                    }
                ],
                "name": "Approve",
                "type": "event"
            },
            {
                "anonymous": false,
                "inputs": [
                    {
                        "indexed": true,
                        "name": "initiator",
                        "type": "address"
                    },
                    {
                        "indexed": false,
                        "name": "contractId",
                        "type": "uint256"
                    }
                ],
                "name": "Execute",
                "type": "event"
            },
            {
                "anonymous": false,
                "inputs": [
                    {
                        "indexed": true,
                        "name": "initiator",
                        "type": "address"
                    },
                    {
                        "indexed": false,
                        "name": "contractId",
                        "type": "uint256"
                    }
                ],
                "name": "Cancel",
                "type": "event"
            }
        ]
                        };
                        Contracts["LicenseContract"] = data;
                        console.log(data);
                        module.exports = data;
                    })((typeof(module) === "undefined" ? {} : module), Contracts);